server:
  port: 8080

cxf:
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics

endpoints:
  jmx:
    enabled: true
    unique-names: true
